### ISSUE TITLE
Multiple folders within .rar not handled

### ISSUE THREAD

**Issue by zach-morris** [xbmc/vfs.libarchive#35]
[example.rar.zip](https://github.com/xbmc/vfs.libarchive/files/3828724/example.rar.zip)

See thread [here](https://forum.kodi.tv/showthread.php?tid=323321&pid=2898237#pid2898237).  Attached is an rar archive (containing srt files) that does not work as expected (I had to zip the rar to attach it):

```
dirs_in_archive, files_in_archive = xbmcvfs.listdir('example.rar')
```

Only returns one folder (of two) and the file in the top directory of the archive.

**Comment by notspiff** [comment]
libarchive does not support solid archives, nothing can be to fix this at the moment.

**Comment by zach-morris** [comment]
Interesting, thanks for the info.  Is 'solid archives' the same as RAR v5?  I see (somewhat recently), support for that was added which mentions solid archives.
https://github.com/libarchive/libarchive/pull/1061

**Comment by notspiff** [comment]
No. Solid archives are orthogonal to rar version.
https://en.m.wikipedia.org/wiki/Solid_compression

**Comment by highlandr** [comment]
Hello guys. I've been testing this problem and the RAR plugin can get the files inside the directories. It flatout the files but when you choose one it tries to copy it from the subdirectory which it doesn't exist since for the plugin everything is at the root...
Spiff what can we do to help RAR plugin or Archive plugin work with these kind of rar's? Code?
Thanks.

Regards.

**Comment by zach-morris** [comment]
I think a possible solution would be something like xbmcvfs.extractall (or something like that), where the archive is extracted in full to a directory without prior knowledge of the contents

**Comment by highlandr** [comment]
True.

**Comment by notspiff** [comment]
libarchive does NOT support the archives. end of story. the rar plugin is too old to work with rar v4 archives, solid or otherwise.

**Comment by andlabs** [comment]
Hi. Sorry for raising the dead, but this is the only relevant Google search result: is there a documented rationale for libarchive not supporting solid RAR files? Thanks.

**Comment by AlwinEsch** [comment]
With `vfs.libarchive` this become never possible. For this reason I updated the `vfs.rar` to use newest unrar with support for everything (about RAR), currently only on Kodi Matrix.
But shortly after Kodi Leia 18.6 is released (has needed a small change for them) becomes also the `vfs.rar` with RAR5 and Solid State read support available on Leia.

However, avoid the use of solid state for direct playback for RAR packages with several videos, this always requires complete unpacking and can then take time (up to minutes).
Only good for unpacking but not for playback.

Also there is an error (or rather missing part) in Kodi, if `vfs.libarchive` and `vfs.rar` are activated, only the first one is taken. Therefore, `vfs.libarchive` should then be deactivated or the`.rar` text removed here https://github.com/xbmc/vfs.libarchive/blob/Leia/vfs.libarchive/addon.xml.in#L11

**Comment by andlabs** [comment]
Ah, in my case I'm looking to use libarchive directly in a non-Kodi capacity, and had assumed @notspiff's first comment above was specifically referring to upstream's intent. Sorry for the confusion! Your explanation makes sense for your use case, in any case.

**Comment by notspiff** [comment]
Upstream, or at least some dev on their ussur tracker, has expressed the
view that since libarchive is all about 'streaming' data directly from
archives, solid archives which by nature requires complete extraction to
get at single files is not within their target domain. Which is kinda
silly, since tar.xxx is supported and that is basically the same. I cannot
find the link now. That being said there appears to be activity regarding
solid archives in their git so maybe tides have changed.

**Comment by zach-morris** [comment]
FWIW, if vfs.rar can handle solid archives, this could potentially be solved on the python side of Kodi as well.  I've created a script module for addon creators that hopefully will help interface with vfs.libarchive and vfs.rar:
https://github.com/zach-morris/script.module.archive_tool
